#!/usr/bin/env python
# coding: utf-8

# In[5]:


from nltk.corpus import wordnet as wn
wn.synsets('motorcar')


# In[7]:


wn.synset('car.n.01').lemmas()


# In[8]:


wn.synset('car.n.01').definition()


# In[9]:


wn.lemma('car.n.01.automobile').synset()


# In[10]:


wn.lemma('car.n.01.automobile').name()


# In[17]:


for synset in wn.synsets('car'):
    print (synset.lemma_names())


# In[22]:


motorcar.hypernyms()


# In[19]:


types_of_motorcar = motorcar.hyponyms()


# In[20]:


types_of_motorcar[26]


# In[ ]:




