#!/usr/bin/env python
# coding: utf-8

# In[1]:


import nltk

with open('document.txt', 'r') as f:
    text = f.read()

new_text = text.replace('the', 'the big brown fox')

print(new_text)


# In[ ]:




